<a href="https://colab.research.google.com/github/KiranSinha872/data_science_june/blob/main/pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np

import pandas as pd

dct1={
    "name":['harry','kiran','sinha','shu'],
    "marks":[92,93,91,89],
    "city":['delhi','silchar','ghy','dorom']
}

df=pd.DataFrame(dct1)

# df # to print

df.to_csv('friends.csv',index =False) # to convert it into a pdf an to remove the index


# starting 2 rows
df.head(2)

#end 2 rows
# df.tail(2)


#gives all mathematical values
df.describe()






#read

dummy=pd.read_csv('dummy_trains.csv')

dummy#print


#access
# dummy['speed']
# dummy


#change data

# dummy['speed'][0]=24
# dummy

# i want to write it in csv again
# dummy.to_csv("dummy_trains.csv")



# access index or change

dummy.index=[1,2,3,4,5,6] #row wise
dummy

   Unnamed: 0  train_no  speed         city
1           0     12001     24    New Delhi
2           1     12002     95       Mumbai
3           2     12627    130      Chennai
4           3     12951    105    Ahmedabad
5           4     12301    115      Kolkata
6           5     22823    125  Bhubaneswar

In [74]:
#creating a data frame

ser=pd.Series(np.random.rand(34))
ser
#data frmae creatinon
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
# type(newdf)
# newdf.head()
# newdf.describe()
# newdf[0][0]='harry'
newdf.head(4)

#transpose
# newdf.T

# newdf.sort_index(axis=1, ascending =False)


# newdf.index#Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
      #  ...
      #  324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      # dtype='int64', length=334)

# newdf.columns #RangeIndex(start=0, stop=5, step=1)


#converting dataframe into numpy array
# newdf.to_numpy()


#view

# newdf2=newdf
# newdf2 is a view
# jaha jaha newdf2 change hoga waha newdf bhi change hoga
# newdf2[0][0]=32527
# newdf2.head()
# newdf.head()



# #copy

# newdf2=newdf.copy()
# newdf2[0][0]=32527
# newdf
# # ab newdf chnage nhi hogi


# view return hoga ya copy?
# isliye ham .loc use krte he
#loc return a new datafrMe keeping the original lsmae


# newdf.loc[0,0]=654
# newdf.head()
#column change
newdf.columns=list("abcde")
newdf.head()




# .iloc
# newdf.iloc[0,4]
# newdf.iloc[[0,3],[1,2]]



#drop colomns

newdf.drop(['a',],axis=1)
# inplace=True matlab newdf me originally hojayega

# newdf.reser_index()
# index reset krdega
# sathme index naamka colomn bhi ayega ijisko drop=True krke hata sakte he


# isnull() #return true or false


##drop_duplicates(subsert=['colomn name or index'],keep='first/false')

#df.shape #shape batayega

            b         c         d         e
0    0.388422  0.563165  0.272246  0.344833
1    0.986616  0.400667  0.071619  0.579910
2    0.839070  0.297624  0.392907  0.273865
3    0.900602  0.534864  0.209408  0.035604
4    0.386585  0.097984  0.597465  0.049492
..        ...       ...       ...       ...
329  0.294702  0.350654  0.791816  0.833179
330  0.625517  0.954110  0.987622  0.283680
331  0.782445  0.755239  0.735929  0.863939
332  0.891264  0.449984  0.225723  0.755356
333  0.825187  0.516915  0.194035  0.731747

[334 rows x 4 columns]